# This file was generated by GoReleaser. DO NOT EDIT.
cask "openmcf" do
  name "openmcf"
  desc "OpenMCF CLI - Infrastructure as Code made simple"
  homepage "https://github.com/plantonhq/openmcf"
  version "0.3.39"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "openmcf"

  on_macos do
    on_intel do
      url "https://github.com/plantonhq/openmcf/releases/download/v#{version}/cli_#{version}_darwin_amd64.tar.gz"
      sha256 "11a34b5cbbe08c3f111cc9d4551400468b0dba8f6ec25e9855ba901a26f2760a"
    end
    on_arm do
      url "https://github.com/plantonhq/openmcf/releases/download/v#{version}/cli_#{version}_darwin_arm64.tar.gz"
      sha256 "78272061026fbf66077680830bd992ef00c8c26b09e38349adeb04a0c962892d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/plantonhq/openmcf/releases/download/v#{version}/cli_#{version}_linux_amd64.tar.gz"
      sha256 "7bf55efd7db37364019b18270a22fde44e00ebbf4e68cb0387dacdffc6b65cf7"
    end
    on_arm do
      url "https://github.com/plantonhq/openmcf/releases/download/v#{version}/cli_#{version}_linux_arm64.tar.gz"
      sha256 "d9eb0dfb4d5cfce3c78a3b89f4bd8cb3fa97d7f4d39edf0cfb6552bfdec7a455"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/openmcf"]
    end
  end

  caveats do
    "Installation Complete!"
    ""
    "OpenMCF CLI helps you manage infrastructure deployments."
    ""
    "Quick Start"
    ""
    "1. Check the version:"
    "   openmcf version"
    ""
    "2. Get help:"
    "   openmcf --help"
    ""
    "Documentation: https://github.com/plantonhq/openmcf"
  end

  # No zap stanza required
end
