# This file was generated by GoReleaser. DO NOT EDIT.
cask "openmcf" do
  name "openmcf"
  desc "OpenMCF CLI - Infrastructure as Code made simple"
  homepage "https://github.com/plantonhq/openmcf"
  version "0.3.36-cli.20260209.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "openmcf"

  on_macos do
    on_intel do
      url "https://github.com/plantonhq/openmcf/releases/download/v#{version}/cli_#{version}_darwin_amd64.tar.gz"
      sha256 "0ec67339b384029578ed7c357059253dc7d4d67a3a02a93b0154bed357b0c18a"
    end
    on_arm do
      url "https://github.com/plantonhq/openmcf/releases/download/v#{version}/cli_#{version}_darwin_arm64.tar.gz"
      sha256 "da71d0dfc8d7f742cef8e7230f200c6f2591ac520c0c9a5a9bab2861a7f9fc5c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/plantonhq/openmcf/releases/download/v#{version}/cli_#{version}_linux_amd64.tar.gz"
      sha256 "6dca1c6153a904a0d5664b61f0f301656e39f08df340d0ddb962984d5873f607"
    end
    on_arm do
      url "https://github.com/plantonhq/openmcf/releases/download/v#{version}/cli_#{version}_linux_arm64.tar.gz"
      sha256 "1f179a0a87290f395fdc9c624e99b5111069f09afc61fa29d523a8ec141b6479"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/openmcf"]
    end
  end

  caveats do
    "Installation Complete!"
    ""
    "OpenMCF CLI helps you manage infrastructure deployments."
    ""
    "Quick Start"
    ""
    "1. Check the version:"
    "   openmcf version"
    ""
    "2. Get help:"
    "   openmcf --help"
    ""
    "Documentation: https://github.com/plantonhq/openmcf"
  end

  # No zap stanza required
end
