# This file was generated by GoReleaser. DO NOT EDIT.
cask "openmcf" do
  name "openmcf"
  desc "OpenMCF CLI - Infrastructure as Code made simple"
  homepage "https://github.com/plantonhq/openmcf"
  version "0.3.42"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "openmcf"

  on_macos do
    on_intel do
      url "https://github.com/plantonhq/openmcf/releases/download/v#{version}/cli_#{version}_darwin_amd64.tar.gz"
      sha256 "2fc039651302f712d5d3b74c88bb7216255a12e0d89144aefce465f6acde1a35"
    end
    on_arm do
      url "https://github.com/plantonhq/openmcf/releases/download/v#{version}/cli_#{version}_darwin_arm64.tar.gz"
      sha256 "56f29d20bc288aee46593b351a41e555b43726f1585c5dd0feeb06ceeae72f71"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/plantonhq/openmcf/releases/download/v#{version}/cli_#{version}_linux_amd64.tar.gz"
      sha256 "215193f84899795b1709056a176928431e2c5360aac15d16d4030d25604c6215"
    end
    on_arm do
      url "https://github.com/plantonhq/openmcf/releases/download/v#{version}/cli_#{version}_linux_arm64.tar.gz"
      sha256 "8fefef962c0822a85210c7fdf11b38cd16a84f0051d822d99f9732de94142564"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/openmcf"]
    end
  end

  caveats do
    "Installation Complete!"
    ""
    "OpenMCF CLI helps you manage infrastructure deployments."
    ""
    "Quick Start"
    ""
    "1. Check the version:"
    "   openmcf version"
    ""
    "2. Get help:"
    "   openmcf --help"
    ""
    "Documentation: https://github.com/plantonhq/openmcf"
  end

  # No zap stanza required
end
