# This file was generated by GoReleaser. DO NOT EDIT.
cask "project-planton" do
  name "project-planton"
  desc "Project Planton CLI - Infrastructure as Code made simple"
  homepage "https://github.com/plantonhq/project-planton"
  version "0.3.13"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "project-planton"

  on_macos do
    on_intel do
      url "https://github.com/plantonhq/project-planton/releases/download/v#{version}/cli_#{version}_darwin_amd64.tar.gz"
      sha256 "03bd7088693211e952357a9eb5a376e5f9de07c9ac9ad24ad75193e8fea732b8"
    end
    on_arm do
      url "https://github.com/plantonhq/project-planton/releases/download/v#{version}/cli_#{version}_darwin_arm64.tar.gz"
      sha256 "c9476882c17372c949319df0418f648b2587e8b3bbe917b4a17d1feef11a5e8e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/plantonhq/project-planton/releases/download/v#{version}/cli_#{version}_linux_amd64.tar.gz"
      sha256 "e5e5b82335392736b08040ce437464185147f849c907b46d1e709c1e87585622"
    end
    on_arm do
      url "https://github.com/plantonhq/project-planton/releases/download/v#{version}/cli_#{version}_linux_arm64.tar.gz"
      sha256 "b7f21b44a1a75c6a5891ef933a5a3e08401b39b1b06d73ac5ccee41ae922b9f8"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/project-planton"]
    end
  end

  caveats do
    "Installation Complete!"
    ""
    "Project Planton CLI helps you manage infrastructure deployments."
    ""
    "Quick Start"
    ""
    "1. Check the version:"
    "   project-planton version"
    ""
    "2. Get help:"
    "   project-planton --help"
    ""
    "Documentation: https://github.com/plantonhq/project-planton"
  end

  # No zap stanza required
end
