# This file was generated by GoReleaser. DO NOT EDIT.
cask "project-planton" do
  name "project-planton"
  desc "Project Planton CLI - Infrastructure as Code made simple"
  homepage "https://github.com/plantonhq/project-planton"
  version "0.2.282"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "project-planton"

  on_macos do
    on_intel do
      url "https://github.com/plantonhq/project-planton/releases/download/v#{version}/project-planton_#{version}_darwin_amd64.tar.gz"
      sha256 "3beac1812940ccf94e2e1760d7d521429c058c93373841b499c51d34654157c8"
    end
    on_arm do
      url "https://github.com/plantonhq/project-planton/releases/download/v#{version}/project-planton_#{version}_darwin_arm64.tar.gz"
      sha256 "5b46650bd19df1b832feff283b3fd1250b8c482efccaa45a85d759b6ca2c75a9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/plantonhq/project-planton/releases/download/v#{version}/project-planton_#{version}_linux_amd64.tar.gz"
      sha256 "4040db6c20d0ace6e26c2a874b8fc0ad03b047e76c7da9ea7ffa93cb193f5ab6"
    end
    on_arm do
      url "https://github.com/plantonhq/project-planton/releases/download/v#{version}/project-planton_#{version}_linux_arm64.tar.gz"
      sha256 "9b450ba37862708685b2739b853a2a481879afce37930980dcf73ea8bd39970b"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/project-planton"]
    end
  end

  caveats do
    "Installation Complete!"
    ""
    "Project Planton CLI helps you manage infrastructure deployments."
    ""
    "Quick Start"
    ""
    "1. Check the version:"
    "   project-planton version"
    ""
    "2. Get help:"
    "   project-planton --help"
    ""
    "Documentation: https://github.com/plantonhq/project-planton"
  end

  # No zap stanza required
end
