# This file was generated by GoReleaser. DO NOT EDIT.
cask "project-planton" do
  name "project-planton"
  desc "Project Planton CLI - Infrastructure as Code made simple"
  homepage "https://github.com/plantonhq/project-planton"
  version "0.3.30-cli.20260120.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "project-planton"

  on_macos do
    on_intel do
      url "https://github.com/plantonhq/project-planton/releases/download/v#{version}/cli_#{version}_darwin_amd64.tar.gz"
      sha256 "755e5a45a4ac738501d419c8488099102a6a840cb42af3bd6971fd6c08e3159d"
    end
    on_arm do
      url "https://github.com/plantonhq/project-planton/releases/download/v#{version}/cli_#{version}_darwin_arm64.tar.gz"
      sha256 "ab580d1c55548eb1f68f91a1c282d40ea7031a4e940c85adecfc59c352ff7119"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/plantonhq/project-planton/releases/download/v#{version}/cli_#{version}_linux_amd64.tar.gz"
      sha256 "52306f702f925eb990686e6f096bcc4fc7c334e3fe110def77d2292cd99d64ab"
    end
    on_arm do
      url "https://github.com/plantonhq/project-planton/releases/download/v#{version}/cli_#{version}_linux_arm64.tar.gz"
      sha256 "4ba42789cf2b6ce63ea660b91f8a60e80e2ebeac7a6324432f230a219eb92bce"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/project-planton"]
    end
  end

  caveats do
    "Installation Complete!"
    ""
    "Project Planton CLI helps you manage infrastructure deployments."
    ""
    "Quick Start"
    ""
    "1. Check the version:"
    "   project-planton version"
    ""
    "2. Get help:"
    "   project-planton --help"
    ""
    "Documentation: https://github.com/plantonhq/project-planton"
  end

  # No zap stanza required
end
